// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoBackend.Repositorio.Contexto;

#nullable disable

namespace ProjetoBackend.Repositorio.Migrations
{
    [DbContext(typeof(ProjetoContexto))]
    [Migration("20260114235731_CriarStoredProceduresUsuario")]
    partial class CriarStoredProceduresUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoBackend.Dominio.Entidade.Evolucao", b =>
                {
                    b.Property<int>("EvolucaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EvolucaoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvolucaoId"));

                    b.Property<decimal?>("BracoCm")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("BracoCm");

                    b.Property<decimal?>("CinturaCm")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("CinturaCm");

                    b.Property<decimal?>("CoxaCm")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("CoxaCm");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataRegistro");

                    b.Property<decimal>("PesoKg")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PesoKg");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioId");

                    b.HasKey("EvolucaoId");

                    b.HasIndex("DataRegistro");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Evolucoes", (string)null);
                });

            modelBuilder.Entity("ProjetoBackend.Dominio.Entidade.Exercicio", b =>
                {
                    b.Property<int>("ExercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ExercicioId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExercicioId"));

                    b.Property<string>("Equipamento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Equipamento");

                    b.Property<string>("GrupoMuscular")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("GrupoMuscular");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nome");

                    b.HasKey("ExercicioId");

                    b.ToTable("Exercicios", (string)null);
                });

            modelBuilder.Entity("ProjetoBackend.Dominio.Entidade.IAInteracao", b =>
                {
                    b.Property<int>("IAInteracaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IAInteracaoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IAInteracaoId"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataHora");

                    b.Property<string>("Pergunta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Pergunta");

                    b.Property<string>("Resposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Resposta");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioId");

                    b.HasKey("IAInteracaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("IAInteracoes", (string)null);
                });

            modelBuilder.Entity("ProjetoBackend.Dominio.Entidade.Treino", b =>
                {
                    b.Property<int>("TreinoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TreinoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreinoId"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCriacao");

                    b.Property<string>("NomeTreino")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NomeTreino");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioId");

                    b.HasKey("TreinoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Treinos", (string)null);
                });

            modelBuilder.Entity("ProjetoBackend.Dominio.Entidade.TreinoExercicio", b =>
                {
                    b.Property<int>("TreinoExercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TreinoExercicioId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreinoExercicioId"));

                    b.Property<int>("DescansoSegundos")
                        .HasColumnType("int")
                        .HasColumnName("DescansoSegundos");

                    b.Property<int>("ExercicioId")
                        .HasColumnType("int")
                        .HasColumnName("ExercicioId");

                    b.Property<int>("Repeticoes")
                        .HasColumnType("int")
                        .HasColumnName("Repeticoes");

                    b.Property<int>("Series")
                        .HasColumnType("int")
                        .HasColumnName("Series");

                    b.Property<int>("TreinoId")
                        .HasColumnType("int")
                        .HasColumnName("TreinoId");

                    b.HasKey("TreinoExercicioId");

                    b.HasIndex("ExercicioId");

                    b.HasIndex("TreinoId");

                    b.ToTable("TreinoExercicios", (string)null);
                });

            modelBuilder.Entity("ProjetoBackend.Dominio.Entidade.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<decimal>("AlturaCm")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("AlturaCm");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCriacao")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataNascimento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SenhaHash");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("ProjetoBackend.Dominio.Entidade.Evolucao", b =>
                {
                    b.HasOne("ProjetoBackend.Dominio.Entidade.Usuario", "Usuario")
                        .WithMany("Evolucoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoBackend.Dominio.Entidade.IAInteracao", b =>
                {
                    b.HasOne("ProjetoBackend.Dominio.Entidade.Usuario", "Usuario")
                        .WithMany("IAInteracoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoBackend.Dominio.Entidade.Treino", b =>
                {
                    b.HasOne("ProjetoBackend.Dominio.Entidade.Usuario", "Usuario")
                        .WithMany("Treinos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoBackend.Dominio.Entidade.TreinoExercicio", b =>
                {
                    b.HasOne("ProjetoBackend.Dominio.Entidade.Exercicio", "Exercicio")
                        .WithMany("TreinoExercicios")
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoBackend.Dominio.Entidade.Treino", "Treino")
                        .WithMany("TreinoExercicios")
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercicio");

                    b.Navigation("Treino");
                });

            modelBuilder.Entity("ProjetoBackend.Dominio.Entidade.Exercicio", b =>
                {
                    b.Navigation("TreinoExercicios");
                });

            modelBuilder.Entity("ProjetoBackend.Dominio.Entidade.Treino", b =>
                {
                    b.Navigation("TreinoExercicios");
                });

            modelBuilder.Entity("ProjetoBackend.Dominio.Entidade.Usuario", b =>
                {
                    b.Navigation("Evolucoes");

                    b.Navigation("IAInteracoes");

                    b.Navigation("Treinos");
                });
#pragma warning restore 612, 618
        }
    }
}
